/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _wolffycode_dsh_engine_suite_engineSuiteGateway_cancelAgent_parameter_0$schema = z.string()
const _wolffycode_dsh_engine_suite_engineSuiteGateway_cancelAgent_result$schema = z.void()
const _wolffycode_dsh_engine_suite_engineSuiteGateway_catalog_result$schema = z.object({
  'engines': z.array(z.object({
  'id': z.string().readonly(),
  'type': z.string().readonly(),
  'displayName': z.string().readonly(),
  'capabilities': z.object({
  'streaming': z.boolean().readonly(),
  'sessionResume': z.boolean().readonly(),
  'modelDiscovery': z.boolean().readonly(),
  'reasoningDiscovery': z.boolean().readonly(),
  'approvals': z.boolean().readonly(),
  'mcp': z.boolean().readonly(),
  'skills': z.boolean().readonly(),
  'backgroundAgent': z.boolean().readonly(),
  'steer': z.boolean().readonly(),
  'fork': z.boolean().readonly(),
}).readonly(),
})).readonly(),
  'providers': z.array(z.object({
  'id': z.string().readonly(),
  'engineId': z.string().readonly(),
  'name': z.string().readonly(),
  'baseUri': z.string().readonly(),
  'wireApi': z.string().readonly(),
  'authMode': z.string().readonly(),
  'enabled': z.boolean().readonly(),
  'status': z.string().readonly(),
})).readonly(),
  'models': z.array(z.object({
  'id': z.string().readonly(),
  'engineId': z.string().readonly(),
  'providerId': z.string().readonly(),
  'modelId': z.string().readonly(),
  'displayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'description': z.union([z.undefined(), z.string()]).readonly().optional(),
  'enabled': z.boolean().readonly(),
  'hidden': z.boolean().readonly(),
  'reasoningOptions': z.array(z.object({
  'id': z.string().readonly(),
  'description': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'defaultReasoningEffort': z.union([z.undefined(), z.string()]).readonly().optional(),
  'inputModalities': z.array(z.string()).readonly(),
  'contextWindowTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
  'contextWindowSource': z.string().readonly(),
  'source': z.string().readonly(),
})).readonly(),
  'profiles': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'engineId': z.string().readonly(),
  'providerId': z.string().readonly(),
  'modelRecordId': z.string().readonly(),
  'reasoningEffort': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillSetRef': z.union([z.undefined(), z.string()]).readonly().optional(),
  'mcpSetRef': z.union([z.undefined(), z.string()]).readonly().optional(),
  'allowedChildProfiles': z.array(z.string()).readonly(),
  'maxChildDepth': z.number().readonly(),
  'maxConcurrentChildren': z.number().readonly(),
  'enabled': z.boolean().readonly(),
})).readonly(),
  'skillSets': z.array(z.object({
  'id': z.string().readonly(),
  'pluginDirs': z.array(z.string()).readonly(),
  'additionalDirectories': z.array(z.string()).readonly(),
})).readonly(),
  'mcpSets': z.array(z.object({
  'id': z.string().readonly(),
  'servers': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'transport': z.string().readonly(),
})).readonly(),
})).readonly(),
})
const _wolffycode_dsh_engine_suite_engineSuiteGateway_createAgent_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'selection': z.object({
  'engineId': z.string().readonly(),
  'providerId': z.string().readonly(),
  'modelRecordId': z.string().readonly(),
  'reasoningEffort': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'cwd': z.string().readonly(),
})
const _wolffycode_dsh_engine_suite_engineSuiteGateway_createAgent_result$schema = z.object({
  'sessionId': z.string().readonly(),
  'agentId': z.string().readonly(),
  'profileId': z.string().readonly(),
})
const _wolffycode_dsh_engine_suite_engineSuiteGateway_discoverModels_parameter_0$schema = z.string()
const _wolffycode_dsh_engine_suite_engineSuiteGateway_discoverModels_result$schema = z.object({
  'models': z.array(z.object({
  'id': z.string().readonly(),
  'engineId': z.string().readonly(),
  'providerId': z.string().readonly(),
  'modelId': z.string().readonly(),
  'displayName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'description': z.union([z.undefined(), z.string()]).readonly().optional(),
  'enabled': z.boolean().readonly(),
  'hidden': z.boolean().readonly(),
  'reasoningOptions': z.array(z.object({
  'id': z.string().readonly(),
  'description': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'defaultReasoningEffort': z.union([z.undefined(), z.string()]).readonly().optional(),
  'inputModalities': z.array(z.string()).readonly(),
  'contextWindowTokens': z.union([z.undefined(), z.number()]).readonly().optional(),
  'contextWindowSource': z.string().readonly(),
  'source': z.string().readonly(),
})).readonly(),
})
const _wolffycode_dsh_engine_suite_engineSuiteGateway_sessionCommands_parameter_0$schema = z.string()
const _wolffycode_dsh_engine_suite_engineSuiteGateway_sessionCommands_parameter_1$schema = z.boolean()
const _wolffycode_dsh_engine_suite_engineSuiteGateway_sessionCommands_result$schema = z.object({
  'sessionId': z.string().readonly(),
  'commands': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'argumentHint': z.string().readonly(),
  'source': z.union([z.literal("command"), z.literal("skill")]).readonly(),
})).readonly(),
})
const _wolffycode_dsh_engine_suite_engineSuiteGateway_switchAgent_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'selection': z.object({
  'engineId': z.string().readonly(),
  'providerId': z.string().readonly(),
  'modelRecordId': z.string().readonly(),
  'reasoningEffort': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
})
const _wolffycode_dsh_engine_suite_engineSuiteGateway_switchAgent_result$schema = z.object({
  'sessionId': z.string().readonly(),
  'agentId': z.string().readonly(),
  'profileId': z.string().readonly(),
})

export const TYPERT = {
  package: '@wolffycode/dsh-engine-suite',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@wolffycode/dsh-engine-suite#engineSuiteGateway/cancelAgent',
      service: 'engineSuiteGateway',
      namespace: 'engineSuiteGateway',
      method: 'cancelAgent',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'agentId',
          wire: 'agentId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@wolffycode/dsh-engine-suite#engineSuiteGateway/cancelAgent:agentId',
            schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_cancelAgent_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@wolffycode/dsh-engine-suite#engineSuiteGateway/cancelAgent:result',
        schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_cancelAgent_result$schema,
      },
      sourceLocation: {"file":"packages/engine-suite/src/remote.ts","line":283,"column":9},
    },
    {
      id: '@wolffycode/dsh-engine-suite#engineSuiteGateway/catalog',
      service: 'engineSuiteGateway',
      namespace: 'engineSuiteGateway',
      method: 'catalog',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@wolffycode/dsh-engine-suite/types#EngineSuiteCatalogView',
        schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_catalog_result$schema,
      },
      sourceLocation: {"file":"packages/engine-suite/src/remote.ts","line":48,"column":9},
    },
    {
      id: '@wolffycode/dsh-engine-suite#engineSuiteGateway/createAgent',
      service: 'engineSuiteGateway',
      namespace: 'engineSuiteGateway',
      method: 'createAgent',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@wolffycode/dsh-engine-suite/types#EngineSuiteCreateAgentRequest',
            schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_createAgent_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@wolffycode/dsh-engine-suite/types#EngineSuiteCreateAgentResponse',
        schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_createAgent_result$schema,
      },
      sourceLocation: {"file":"packages/engine-suite/src/remote.ts","line":185,"column":9},
    },
    {
      id: '@wolffycode/dsh-engine-suite#engineSuiteGateway/discoverModels',
      service: 'engineSuiteGateway',
      namespace: 'engineSuiteGateway',
      method: 'discoverModels',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'providerId',
          wire: 'providerId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@wolffycode/dsh-engine-suite#engineSuiteGateway/discoverModels:providerId',
            schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_discoverModels_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@wolffycode/dsh-engine-suite/types#EngineSuiteDiscoverModelsResponse',
        schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_discoverModels_result$schema,
      },
      sourceLocation: {"file":"packages/engine-suite/src/remote.ts","line":246,"column":9},
    },
    {
      id: '@wolffycode/dsh-engine-suite#engineSuiteGateway/sessionCommands',
      service: 'engineSuiteGateway',
      namespace: 'engineSuiteGateway',
      method: 'sessionCommands',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@wolffycode/dsh-engine-suite#engineSuiteGateway/sessionCommands:sessionId',
            schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_sessionCommands_parameter_0$schema,
          },
        },
        {
          name: 'refresh',
          wire: 'refresh',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@wolffycode/dsh-engine-suite#engineSuiteGateway/sessionCommands:refresh',
            schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_sessionCommands_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@wolffycode/dsh-engine-suite/types#EngineSuiteCommandsResponse',
        schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_sessionCommands_result$schema,
      },
      sourceLocation: {"file":"packages/engine-suite/src/remote.ts","line":235,"column":9},
    },
    {
      id: '@wolffycode/dsh-engine-suite#engineSuiteGateway/switchAgent',
      service: 'engineSuiteGateway',
      namespace: 'engineSuiteGateway',
      method: 'switchAgent',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@wolffycode/dsh-engine-suite/types#EngineSuiteSwitchAgentRequest',
            schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_switchAgent_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@wolffycode/dsh-engine-suite/types#EngineSuiteSwitchAgentResponse',
        schema: _wolffycode_dsh_engine_suite_engineSuiteGateway_switchAgent_result$schema,
      },
      sourceLocation: {"file":"packages/engine-suite/src/remote.ts","line":214,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "engineSuite",
        "exportName": "EngineSuiteService",
        "members": [],
        "types": []
      },
      {
        "description": "Host remote surface used by the client selector and settings UI.",
        "summary": "Host remote surface used by the client selector and settings UI.",
        "tags": [],
        "jsDoc": "/** Host remote surface used by the client selector and settings UI. */",
        "key": "engineSuiteGateway",
        "exportName": "EngineSuiteGateway",
        "members": [
          {
            "kind": "method",
            "name": "catalog",
            "signature": "@Remote('catalog') async catalog(): Promise<EngineSuiteCatalogView>"
          },
          {
            "kind": "method",
            "name": "createAgent",
            "signature": "@Remote('createAgent') async createAgent(request: EngineSuiteCreateAgentRequest): Promise<EngineSuiteCreateAgentResponse>"
          },
          {
            "kind": "method",
            "name": "switchAgent",
            "signature": "@Remote('switchAgent') async switchAgent(request: EngineSuiteSwitchAgentRequest): Promise<EngineSuiteSwitchAgentResponse>"
          },
          {
            "kind": "method",
            "name": "sessionCommands",
            "signature": "@Remote('sessionCommands') async sessionCommands(sessionId: string, refresh: boolean): Promise<EngineSuiteCommandsResponse>"
          },
          {
            "kind": "method",
            "name": "discoverModels",
            "signature": "@Remote('discoverModels') async discoverModels(providerId: string): Promise<EngineSuiteDiscoverModelsResponse>"
          },
          {
            "kind": "method",
            "name": "cancelAgent",
            "signature": "@Remote('cancelAgent') async cancelAgent(agentId: string): Promise<void>"
          }
        ],
        "types": [
          {
            "name": "EngineSuiteCatalogView",
            "declaration": "export interface EngineSuiteCatalogView {\n    readonly engines: readonly EngineSuiteEngineView[];\n    readonly providers: readonly EngineSuiteProviderView[];\n    readonly models: readonly EngineSuiteModelView[];\n    readonly profiles: readonly EngineSuiteProfileView[];\n    readonly skillSets: readonly EngineSuiteSkillSetView[];\n    readonly mcpSets: readonly EngineSuiteMcpSetView[];\n}"
          },
          {
            "name": "EngineSuiteCommandSource",
            "declaration": "export type EngineSuiteCommandSource = 'command' | 'skill';"
          },
          {
            "name": "EngineSuiteCommandsResponse",
            "declaration": "export interface EngineSuiteCommandsResponse {\n    readonly sessionId: string;\n    readonly commands: readonly EngineSuiteCommandView[];\n}"
          },
          {
            "name": "EngineSuiteCommandView",
            "declaration": "export interface EngineSuiteCommandView {\n    readonly name: string;\n    readonly description: string;\n    readonly argumentHint: string;\n    readonly source: EngineSuiteCommandSource;\n}"
          },
          {
            "name": "EngineSuiteCreateAgentRequest",
            "declaration": "export interface EngineSuiteCreateAgentRequest {\n    readonly sessionId: string;\n    readonly selection: EngineSuiteSelectionRequest;\n    readonly cwd: string;\n}"
          },
          {
            "name": "EngineSuiteCreateAgentResponse",
            "declaration": "export interface EngineSuiteCreateAgentResponse {\n    readonly sessionId: string;\n    readonly agentId: string;\n    readonly profileId: string;\n}"
          },
          {
            "name": "EngineSuiteDiscoverModelsResponse",
            "declaration": "export interface EngineSuiteDiscoverModelsResponse {\n    readonly models: readonly EngineSuiteModelView[];\n}"
          },
          {
            "name": "EngineSuiteEngineView",
            "declaration": "export interface EngineSuiteEngineView {\n    readonly id: string;\n    readonly type: string;\n    readonly displayName: string;\n    readonly capabilities: { readonly streaming: boolean; readonly sessionResume: boolean; readonly modelDiscovery: boolean; readonly reasoningDiscovery: boolean; readonly approvals: boolean; readonly mcp: boolean; readonly skills: boolean; readonly backgroundAgent: boolean; readonly steer: boolean; readonly fork: boolean; };\n}"
          },
          {
            "name": "EngineSuiteMcpServerView",
            "declaration": "export interface EngineSuiteMcpServerView {\n    readonly id: string;\n    readonly name: string;\n    readonly transport: string;\n}"
          },
          {
            "name": "EngineSuiteMcpSetView",
            "declaration": "export interface EngineSuiteMcpSetView {\n    readonly id: string;\n    readonly servers: readonly EngineSuiteMcpServerView[];\n}"
          },
          {
            "name": "EngineSuiteModelView",
            "declaration": "export interface EngineSuiteModelView {\n    readonly id: string;\n    readonly engineId: string;\n    readonly providerId: string;\n    readonly modelId: string;\n    readonly displayName?: string;\n    readonly description?: string;\n    readonly enabled: boolean;\n    readonly hidden: boolean;\n    readonly reasoningOptions: readonly EngineSuiteReasoningOptionView[];\n    readonly defaultReasoningEffort?: string;\n    readonly inputModalities: readonly string[];\n    readonly contextWindowTokens?: number;\n    readonly contextWindowSource: string;\n    readonly source: string;\n}"
          },
          {
            "name": "EngineSuiteProfileView",
            "declaration": "export interface EngineSuiteProfileView {\n    readonly id: string;\n    readonly name: string;\n    readonly engineId: string;\n    readonly providerId: string;\n    readonly modelRecordId: string;\n    readonly reasoningEffort?: string;\n    readonly skillSetRef?: string;\n    readonly mcpSetRef?: string;\n    readonly allowedChildProfiles: readonly string[];\n    readonly maxChildDepth: number;\n    readonly maxConcurrentChildren: number;\n    readonly enabled: boolean;\n}"
          },
          {
            "name": "EngineSuiteProviderView",
            "declaration": "export interface EngineSuiteProviderView {\n    readonly id: string;\n    readonly engineId: string;\n    readonly name: string;\n    readonly baseUri: string;\n    readonly wireApi: string;\n    readonly authMode: string;\n    readonly enabled: boolean;\n    readonly status: string;\n}"
          },
          {
            "name": "EngineSuiteReasoningOptionView",
            "declaration": "export interface EngineSuiteReasoningOptionView {\n    readonly id: string;\n    readonly description?: string;\n}"
          },
          {
            "name": "EngineSuiteSelectionRequest",
            "declaration": "export interface EngineSuiteSelectionRequest {\n    readonly engineId: string;\n    readonly providerId: string;\n    readonly modelRecordId: string;\n    readonly reasoningEffort?: string;\n}"
          },
          {
            "name": "EngineSuiteSkillSetView",
            "declaration": "export interface EngineSuiteSkillSetView {\n    readonly id: string;\n    readonly pluginDirs: readonly string[];\n    readonly additionalDirectories: readonly string[];\n}"
          },
          {
            "name": "EngineSuiteSwitchAgentRequest",
            "declaration": "export interface EngineSuiteSwitchAgentRequest {\n    readonly sessionId: string;\n    readonly selection: EngineSuiteSelectionRequest;\n}"
          },
          {
            "name": "EngineSuiteSwitchAgentResponse",
            "declaration": "export interface EngineSuiteSwitchAgentResponse {\n    readonly sessionId: string;\n    readonly agentId: string;\n    readonly profileId: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
