/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { EngineSuiteCatalogView, EngineSuiteCommandsResponse, EngineSuiteCreateAgentRequest, EngineSuiteCreateAgentResponse, EngineSuiteDiscoverModelsResponse, EngineSuiteSwitchAgentRequest, EngineSuiteSwitchAgentResponse } from '@wolffycode/dsh-engine-suite/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$656e67696e65537569746547617465776179 {
    cancelAgent: (agentId: string) => Promise<RemoteResult<void>>
    catalog: () => Promise<RemoteResult<EngineSuiteCatalogView>>
    createAgent: (request: EngineSuiteCreateAgentRequest) => Promise<RemoteResult<EngineSuiteCreateAgentResponse>>
    discoverModels: (providerId: string) => Promise<RemoteResult<EngineSuiteDiscoverModelsResponse>>
    sessionCommands: (sessionId: string, refresh: boolean) => Promise<RemoteResult<EngineSuiteCommandsResponse>>
    switchAgent: (request: EngineSuiteSwitchAgentRequest) => Promise<RemoteResult<EngineSuiteSwitchAgentResponse>>
  }
  interface TypertRemoteMap {
    'engineSuiteGateway/cancelAgent': (agentId: string) => Promise<RemoteResult<void>>
    'engineSuiteGateway/catalog': () => Promise<RemoteResult<EngineSuiteCatalogView>>
    'engineSuiteGateway/createAgent': (request: EngineSuiteCreateAgentRequest) => Promise<RemoteResult<EngineSuiteCreateAgentResponse>>
    'engineSuiteGateway/discoverModels': (providerId: string) => Promise<RemoteResult<EngineSuiteDiscoverModelsResponse>>
    'engineSuiteGateway/sessionCommands': (sessionId: string, refresh: boolean) => Promise<RemoteResult<EngineSuiteCommandsResponse>>
    'engineSuiteGateway/switchAgent': (request: EngineSuiteSwitchAgentRequest) => Promise<RemoteResult<EngineSuiteSwitchAgentResponse>>
  }
  interface TypertRemoteNamespaceMap {
    'engineSuiteGateway': TypertRemoteNamespace$656e67696e65537569746547617465776179
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
