import { type AgentDefinition } from '@anthropic-ai/claude-agent-sdk';
import type { ClaudeAdapterEvent, ClaudeAdapterOptions, ClaudeAgentSession, ClaudeCatalog, ClaudePermissionDecision, ClaudePermissionMode, ClaudePermissionRequest, ClaudePersistenceHandle, ClaudeRunResult, ClaudeRewindRequest, ClaudeRewindResult, ClaudeSlashCommand, ClaudeThinkingOption, ClaudeUserQuestionResult } from './types.js';
/** Returns true when a model identifier or SDK catalog row names an Opus model. */
export declare function isOpusModel(value: unknown): boolean;
/** Filters every Claude SDK catalog row whose alias, label, or resolved model is Opus. */
export declare function filterClaudeCatalogModels<T>(models: readonly T[]): T[];
export declare function assertClaudeModelAllowed(model: unknown): void;
export declare function parseClaudeUserAgentDefinitions(value: unknown): Record<string, AgentDefinition> | undefined;
export declare class ClaudeProviderSession implements ClaudeAgentSession {
    readonly capabilities: Readonly<Record<string, boolean>>;
    private readonly options;
    private readonly redactor;
    private readonly userAgentDefinitions;
    private readonly transport;
    private readonly listeners;
    private readonly permissionRegistry;
    private readonly catalogCache;
    private readonly subagentReducer;
    private readonly rewindSdk;
    private readonly persistenceGateway;
    private readonly modelState;
    private readonly modeState;
    private readonly thinkingState;
    private readonly pendingQuestionsMap;
    private readonly toolInputByIndex;
    private readonly toolMetaByIndex;
    private readonly unsubscribeTransport;
    private activeTurn;
    private stderrTail;
    private turnSequence;
    private closed;
    private readonly nativeSessionId;
    private _sessionId;
    private _forked;
    private readyPromise;
    private readyResolve;
    private readyReject;
    private readySettled;
    private readyError;
    private turnStarting;
    private sessionStartedEmitted;
    private _catalog;
    constructor(options: ClaudeAdapterOptions);
    get sessionId(): string | undefined;
    get catalog(): ClaudeCatalog;
    whenReady(): Promise<void>;
    subscribe(listener: (event: ClaudeAdapterEvent) => void): () => void;
    startTurn(prompt: string, options?: {
        readonly clientMessageId?: string;
    }): Promise<{
        readonly turnId: string;
    }>;
    run(prompt: string, options?: {
        readonly clientMessageId?: string;
    }): Promise<ClaudeRunResult>;
    interrupt(): Promise<void>;
    close(): Promise<void>;
    setMode(mode: string): Promise<void>;
    setPermissionMode(mode: ClaudePermissionMode): Promise<void>;
    setModel(model?: string): Promise<void>;
    setThinking(thinking: ClaudeThinkingOption): Promise<void>;
    steer(prompt: string): Promise<{
        readonly status: 'accepted' | 'unavailable';
    }>;
    respondToPermission(requestId: string, decision: ClaudePermissionDecision): boolean;
    respondToUserQuestion(requestId: string, result: ClaudeUserQuestionResult): boolean;
    pendingPermissions(): readonly ClaudePermissionRequest[];
    persistenceHandle(): ClaudePersistenceHandle | undefined;
    history(options?: import('./persistence.js').ClaudeSessionHistoryOptions): Promise<readonly import('@anthropic-ai/claude-agent-sdk').SessionMessage[]>;
    reconnect(): Promise<ClaudeAgentSession>;
    listCommands(): readonly ClaudeSlashCommand[];
    refreshCatalog(): Promise<ClaudeCatalog>;
    rewind(input: ClaudeRewindRequest): Promise<ClaudeRewindResult>;
    private initializeReadiness;
    private resolveReady;
    private rejectReady;
    private failInitialization;
    private closeTransport;
    private applyInitializationResult;
    private beginTurn;
    private applyPendingTurnSettings;
    private applyThinkingToQuery;
    private restoreAppliedTurnSettings;
    private inputMessage;
    private buildSdkOptions;
    private requestPermission;
    private requestUserQuestion;
    private finishUserQuestion;
    private transportQuery;
    private handleTransportEvent;
    private handleMessage;
    private handleSubagentMessage;
    private handleSystem;
    private emitSessionStarted;
    private applyInitialization;
    private handleStreamEvent;
    private emitToolResult;
    private handleAssistant;
    private handleUser;
    private handleResult;
    private emit;
    private mapCatalogCommand;
    private mapCatalogModel;
    private mapCommand;
    private mapModel;
    private mapMcp;
}
//# sourceMappingURL=session.d.ts.map